version: "2"
services:
  db:
    image: mysql:5.7.23
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file: .env
    ports:
      - 33060:3306

  memcached:
    image: memcached:latest

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file: .env
    links:
      - db
    ports:
      - 8080:80
    volumes:
      - /sessions

  wordpress:
    build: ./wordpress/
    working_dir: $WORDPRESS_DOCUMENT_ROOT
    ports:
      - "9000:80"
    depends_on:
      - db
    restart: always
    environment:
      WORDPRESS_DB_HOST: "db:3306"
    env_file: .env
    volumes:
      - ./www_data:$WORDPRESS_DOCUMENT_ROOT
      - ./wordpress/php-config.ini:/usr/local/etc/php/conf.d/php-config.ini
volumes:
  db_data:
    driver: local
